# Credit Default

Tarefa 1: Ler o arquivo com o pandas

In [31]:
import pandas as pd

# realiza a leitura dos dados
dataset = pd.read_csv('../data/lv-credit-card-default-1000.csv',sep=',')
# carrega os dados em um dataframe
data = pd.DataFrame(dataset)
# exibe os dados para verificação
data.tail()

,CUSTID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULTED
997,103,480000.0,M,1.0,1.0,63.0,0.0,0.0,0.0,2.0,...,898.0,325.0,-339603.0,898.0,325.0,898.0,325.0,0.0,345293.0,1
998,388,80000.0,M,3.0,1.0,73.0,-1.0,0.0,0.0,2.0,...,-57.0,127.0,-189.0,0.0,1000.0,0.0,500.0,0.0,1000.0,1
999,247,250000.0,F,2.0,1.0,75.0,0.0,-1.0,-1.0,-1.0,...,-3684.0,0.0,1386.0,10118.0,47015.0,0.0,4000.0,100000.0,10000.0,1
1000,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1001,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Etapa 2: Transformando e selecionando os dados

Após a leitura dos dados é importante identificar quais os campos ordinais que devem ser traduzidos para valores numéricos para que sejam mais facilmente manipulados pelos algoritmos

In [32]:
import numpy as np

# aplica um filtro para alterar dados não padronizados no caso o sexo
maskF = data['SEX'] == "F"
data.iloc[data[maskF].index, 2] = 2
maskF = data['SEX'] == "M"
data.iloc[data[maskF].index, 2] = 1
# deleta todos os registros que possuam algum valor NaN e altera o próprio dataframe
data.dropna(inplace = True)

data.tail()

,CUSTID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULTED
995,932,320000.0,1,1.0,1.0,60.0,-1.0,-1.0,-1.0,-2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
996,367,50000.0,2,2.0,1.0,61.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
997,103,480000.0,1,1.0,1.0,63.0,0.0,0.0,0.0,2.0,...,898.0,325.0,-339603.0,898.0,325.0,898.0,325.0,0.0,345293.0,1
998,388,80000.0,1,3.0,1.0,73.0,-1.0,0.0,0.0,2.0,...,-57.0,127.0,-189.0,0.0,1000.0,0.0,500.0,0.0,1000.0,1
999,247,250000.0,2,2.0,1.0,75.0,0.0,-1.0,-1.0,-1.0,...,-3684.0,0.0,1386.0,10118.0,47015.0,0.0,4000.0,100000.0,10000.0,1

Transformação dos dados: Realizando a normalização dos dados

In [65]:
from sklearn import preprocessing

labelColumn = 'DEFAULTED'
# separa os dados dos rótulos
columns = data.columns.difference([labelColumn])
features = data[columns]
targets = data[labelColumn]
# normaliza os dados
nFeatures = preprocessing.normalize(features)
dataNorm = pd.DataFrame(nFeatures)
# remonta a columa de rótulo nos dados normalizados
# dataNorm.head()

# Etapa 3: Reduzindo a dimensionalidade do problema

Agora é o momento de estabelecer seus critérios de seleção dos campos. Você pode selecionar por métodos de filtragem (Valores faltantes, baixa variância, alta correlação), força bruta (BFE ou FFC) ou executar o PCA. O importante é encontrar um conunto de campos menor que o inicial para reduzir a complexidade computacional.

In [66]:
#from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA

# exemplo de seleção por variância do campo
#selector = VarianceThreshold(0.0)
#dataF = selector.fit_transform(dataNorm)
# remonta o DataFrame
#dataFiltered = pd.DataFrame(dataF)
#dataFiltered.head()

# Create correlation matrix
corr_matrix = dataNorm.corr().abs()
# corr_matrix

# pca = PCA(n_components=3)
# pca.fit(dataNorm)
# dataNorm = pca.transform(dataNorm)
# dataNorm.values

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.000000,0.165229,0.164708,0.181022,0.174156,0.172752,0.173987,0.663324,0.858468,0.137817,...,0.257586,0.617275,0.624196,0.079505,0.031281,0.043619,0.022352,0.014668,0.053710,0.791034
1,0.165229,1.000000,0.810769,0.742880,0.647120,0.584788,0.572170,0.174611,0.193911,0.751158,...,0.003698,0.238392,0.233125,0.023812,0.000242,0.024339,0.023113,0.031500,0.066523,0.232686
2,0.164708,0.810769,1.000000,0.814612,0.730264,0.643398,0.627992,0.157152,0.169135,0.785516,...,0.032424,0.214215,0.221128,0.290275,0.035579,0.047886,0.016519,0.010940,0.029222,0.214611
3,0.181022,0.742880,0.814612,1.000000,0.818421,0.738204,0.690726,0.151185,0.185057,0.793944,...,0.013193,0.262442,0.277900,0.021597,0.298301,0.001879,0.013571,0.006892,0.031789,0.218978
4,0.174156,0.647120,0.730264,0.818421,1.000000,0.830253,0.764231,0.156424,0.164989,0.759895,...,0.002241,0.291525,0.287743,0.018421,0.113955,0.265339,0.005685,0.023321,0.000153,0.213359
5,0.172752,0.584788,0.643398,0.738204,0.830253,1.000000,0.821496,0.143170,0.163166,0.725183,...,0.016172,0.276941,0.315499,0.005446,0.101574,0.083837,0.328621,0.066674,0.019201,0.206903
6,0.173987,0.572170,0.627992,0.690726,0.764231,0.821496,1.000000,0.139615,0.154819,0.703706,...,0.003878,0.242166,0.283726,0.003186,0.038526,0.069500,0.131405,0.259101,0.045440,0.192499
7,0.663324,0.174611,0.157152,0.151185,0.156424,0.143170,0.139615,1.000000,0.712336,0.121992,...,0.132528,0.501198,0.475566,0.120606,0.099845,0.084714,0.066876,0.037849,0.074009,0.779335
8,0.858468,0.193911,0.169135,0.185057,0.164989,0.163166,0.154819,0.712336,1.000000,0.123289,...,0.144007,0.641828,0.614878,0.109746,0.055187,0.080449,0.060162,0.057909,0.141587,0.854986
9,0.137817,0.751158,0.785516,0.793944,0.759895,0.725183,0.703706,0.121992,0.123289,1.000000,...,0.000466,0.154634,0.161866,0.166083,0.196965,0.163622,0.164686,0.192594,0.155360,0.167770
10,0.797280,0.261741,0.231035,0.256584,0.238068,0.223217,0.205070,0.735371,0.856091,0.165633,...,0.116184,0.673877,0.665829,0.187193,0.099847,0.137391,0.116560,0.101836,0.186577,0.871913
11,0.314614,0.022987,0.039054,0.043091,0.045675,0.064873,0.058695,0.208828,0.315328,0.024100,...,0.016490,0.335082,0.336702,0.030161,0.020555,0.044419,0.003972,0.005583,0.040947,0.267284
12,0.324682,0.003606,0.025020,0.037835,0.028411,0.058717,0.041080,0.210780,0.330415,0.000974,...,0.070619,0.279016,0.304462,0.012455,0.002793,0.053443,0.024694,0.019300,0.058966,0.277795
13,0.135384,0.040941,0.052050,0.021647,0.025430,0.038821,0.056627,0.035556,0.020057,0.014076,...,0.768384,0.043659,0.015365,0.034644,0.040176,0.046479,0.036202,0.014260,0.045242,0.076489
14,0.257586,0.003698,0.032424,0.013193,0.002241,0.016172,0.003878,0.132528,0.144007,0.000466,...,1.000000,0.134925,0.132304,0.068329,0.036767,0.029258,0.018336,0.021122,0.032825,0.097252
15,0.617275,0.238392,0.214215,0.262442,0.291525,0.276941,0.242166,0.501198,0.641828,0.154634,...,0.134925,1.000000,0.870372,0.152529,0.042626,0.010970,0.079231,0.069254,0.086727,0.620349
16,0.624196,0.233125,0.221128,0.277900,0.287743,0.315499,0.283726,0.475566,0.614878,0.161866,...,0.132304,0.870372,1.000000,0.159304,0.051387,0.067840,0.015696,0.082924,0.121350,0.626830
17,0.079505,0.023812,0.290275,0.021597,0.018421,0.005446,0.003186,0.120606,0.109746,0.166083,...,0.068329,0.152529,0.159304,1.000000,0.188190,0.255596,0.206764,0.145671,0.230392,0.126667
18,0.031281,0.000242,0.035579,0.298301,0.113955,0.101574,0.038526,0.099845,0.055187,0.196965,...,0.036767,0.042626,0.051387,0.188190,1.000000,0.251580,0.270316,0.164207,0.208774,0.101751
19,0.043619,0.024339,0.047886,0.001879,0.265339,0.083837,0.069500,0.084714,0.080449,0.163622,...,0.029258,0.010970,0.067840,0.255596,0.251580,1.000000,0.215534,0.196878,0.210812,0.099754
20,0.022352,0.023113,0.016519,0.013571,0.005685,0.328621,0.131405,0.066876,0.060162,0.164686,...,0.018336,0.079231,0.015696,0.206764,0.270316,0.215534,1.000000,0.156062,0.203288,0.087064
21,0.014668,0.031500,0.010940,0.006892,0.023321,0.066674,0.259101,0.037849,0.057909,0.192594,...,0.021122,0.069254,0.082924,0.145671,0.164207,0.196878,0.156062,1.000000,0.124408,0.091141
22,0.053710,0.066523,0.029222,0.031789,0.000153,0.019201,0.045440,0.074009,0.141587,0.155360,...,0.032825,0.086727,0.121350,0.230392,0.208774,0.210812,0.203288,0.124408,1.000000,0.155718
23,0.791034,0.232686,0.214611,0.218978,0.213359,0.206903,0.192499,0.779335,0.854986,0.167770,...,0.097252,0.620349,0.626830,0.126667,0.101751,0.099754,0.087064,0.091141,0.155718,1.000000

Seleciona as colunas que devem ser eliminadas por um limiar

In [35]:
# Seleciona somente o triangulo superior da matriz
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
#upper
# Encontra as colunas com variancia menor que 0.85
to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]
#to_drop
dataFiltered = dataNorm.drop(dataNorm.columns[to_drop], axis=1)
dataFiltered['DEFAULTED'] = targets;
dataFiltered.head()

,0,1,2,3,4,5,6,7,9,11,...,13,14,15,17,18,19,20,21,22,DEFAULTED
0,0.000129,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.003247,0.122526,-0.000006,...,0.000012,0.000012,-0.000012,0.000000,0.000000,0.000000,0.0,0.992460,0.000000,0
1,0.000367,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000633,0.999655,0.000000,...,0.000000,0.000000,-0.000033,0.000000,0.000000,0.000000,0.0,0.000000,0.026258,0
2,0.002176,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.004252,0.988925,0.000000,...,0.000000,0.000000,-0.000198,0.000000,0.000000,0.000000,0.0,0.000000,0.148339,0
3,0.000167,0.008579,0.002207,0.004415,0.002207,0.0,0.002207,0.000357,0.151714,0.000000,...,0.000015,-0.000008,0.000000,0.002207,0.004415,0.000000,0.0,0.988345,0.004938,0
4,0.000141,0.010845,0.084927,0.002775,0.011736,0.0,0.018530,0.000449,0.128191,0.000013,...,0.000000,0.000000,-0.000006,0.084927,0.002775,0.011736,0.0,0.018530,0.983894,0

# Etapa 4: Criar e treinar o modelo de classificação

Esse é o momento de escolher qual o algoritmo você quer usar. Usar mais de um (ou um método ensemble) ajuda a ter a noção de qual a melhor estratégia para o problema.

Esse também é o momento de criar as suas bases de treinamento, validação e teste. Realizar a validação cruzada também ajuda bastante e é muito recomendado que o faça

In [42]:
from sklearn import model_selection

from sklearn.model_selection import train_test_split

dataTrain, dataTest = train_test_split(dataFiltered, test_size=0.2)
# cria um modelo de validação cruzada
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)

Cria os estimadores do nosso ensemble

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

# separando os dados denovo
nColumns = dataTrain.shape[1] - 1
trainValues = dataTrain.values
trainFeatures = trainValues[:,0:nColumns-1]
trainTargets = trainValues[:,nColumns]
# cria os preditores
estimators = []
model1 = LogisticRegression()
estimators.append(('logistic', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))
# cria o ensemble
ensemble = VotingClassifier(estimators)
ensemble.fit(trainFeatures, trainTargets)
results = model_selection.cross_val_score(ensemble, trainFeatures, trainTargets, cv=kfold)
print('Accuracy: {0:0.2f}'.format(results.mean()))

AttributeError: 'numpy.ndarray' object has no attribute 'values'

# Etapa 5: Realizar a classificação

In [38]:
testValues = dataTest.values
testFeatures = testValues[:,0:nColumns-1]
testTargets = testValues[:,nColumns]

# realiza a predição sobre a base de teste
predictions = ensemble.predict(testFeatures)

/home/alexander/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

# Etapa 6: Avaliar os resultados da predição

In [39]:
# avalia o resultado 
from sklearn.metrics import accuracy_score
# realiza o calculo da acuracia
accuracy = accuracy_score(testTargets, predictions)
# exibe na tela o resultado final
print('Accuracy: {0:0.2f}'.format(accuracy))

Accuracy: 0.62